from SconsUtils import cunit

Import("env")

programs = Split("""
test_resolver.c
""")

nenv = env.Clone()
nenv.Append(CFLAGS="-Ilibreplace -Ilib ")


cunit.buildCUnitTestFromFiles(nenv, programs,
                              extraObjects = Split(env.liboo_files),
                              LIBS=env.libaff4_so, LIBPATH="#lib/")


#for prog in Split(programs):
#  prog = nenv.Program([prog] + Split(env.liboo_files),
#                      LIBS=env.libaff4_so, LIBPATH="#lib/")
