from SconsUtils import cunit
from SconsUtils import utils

Import("env")

if utils.HEADERS.get("HAVE_CUNIT"):
    programs = Split("""
    resolver.c
    rdfvalues.c
    """)

    nenv = env.Clone()
    nenv.Append(CFLAGS="-Ilibreplace -Ilib ")

    cunit.buildCUnitTestFromFiles(nenv, programs,
                                  extraObjects = Split(env.liboo_files),
                                  LIBS=env.libaff4_so, LIBPATH="#lib/")
else:
    utils.warn("CUnit not found. Skipping unit tests.")
