
/**********************************************************************
     Autogenerated module pytsk3

This module was autogenerated from the following files:
/home/mic/projects/aff4/python2.6/tsk/pytsk3.h
/home/mic/projects/aff4/python2.6/tsk/tsk3.h
/usr/local/include/tsk3/fs/tsk_fs.h
/usr/local/include/tsk3/base/tsk_base.h

This module implements the following classes:
Module pytsk3
    # This is an image info object based on an AFF4 object.

    Before we can use libtsk we need to instantiate one of these from
    a base URN.
 
Class AFF4ImgInfo(Object):
 Constructor: def AFF4ImgInfo Con(ZString : urn , uint64_t  : offset , uint64_t  : type):
 Attributes: 
    RDFURN : urn

 Methods: 
    def uint64_t  read(uint64_t  : off , OUT char * : buf):
    def  close():

    # Base object

Class Object(Obj):
 Constructor: def  Con():
 Attributes: 

 Methods: 

Constants:
 TSK_FS_BLOCK_TAG
 TSK_FS_ATTR_ID_DEFAULT
 TSK_FS_META_NAME_LIST_NSIZE
 TSK_FS_META_TYPE_STR_MAX
 TSK_FS_META_TAG
 TSK_FS_ORPHAN_STR
 TSK_FS_NAME_TYPE_STR_MAX
 TSK_FS_NAME_TAG
 TSK_FS_DIR_TAG
 TSK_FS_FILE_TAG
 TSK_FS_INFO_TAG
 TSK_FS_INFO_FS_ID_LEN
 TSK_VERSION_NUM
 TSK_VERSION_STR
 PRIX64
 PRIX32
 PRIX16
 TSK_ERR_AUX
 TSK_ERR_IMG
 TSK_ERR_VS
 TSK_ERR_FS
 TSK_ERR_HDB
 TSK_ERR_MASK
 TSK_ERR_AUX_MALLOC
 TSK_ERR_AUX_MAX
 TSK_ERR_IMG_NOFILE
 TSK_ERR_IMG_OFFSET
 TSK_ERR_IMG_UNKTYPE
 TSK_ERR_IMG_UNSUPTYPE
 TSK_ERR_IMG_OPEN
 TSK_ERR_IMG_STAT
 TSK_ERR_IMG_SEEK
 TSK_ERR_IMG_READ
 TSK_ERR_IMG_READ_OFF
 TSK_ERR_IMG_ARG
 TSK_ERR_IMG_MAGIC
 TSK_ERR_IMG_WRITE
 TSK_ERR_IMG_CONVERT
 TSK_ERR_IMG_PASSWD
 TSK_ERR_IMG_MAX
 TSK_ERR_VS_UNKTYPE
 TSK_ERR_VS_UNSUPTYPE
 TSK_ERR_VS_READ
 TSK_ERR_VS_MAGIC
 TSK_ERR_VS_WALK_RNG
 TSK_ERR_VS_BUF
 TSK_ERR_VS_BLK_NUM
 TSK_ERR_VS_ARG
 TSK_ERR_VS_MAX
 TSK_ERR_FS_UNKTYPE
 TSK_ERR_FS_UNSUPTYPE
 TSK_ERR_FS_UNSUPFUNC
 TSK_ERR_FS_WALK_RNG
 TSK_ERR_FS_READ
 TSK_ERR_FS_READ_OFF
 TSK_ERR_FS_ARG
 TSK_ERR_FS_BLK_NUM
 TSK_ERR_FS_INODE_NUM
 TSK_ERR_FS_INODE_COR
 TSK_ERR_FS_MAGIC
 TSK_ERR_FS_FWALK
 TSK_ERR_FS_WRITE
 TSK_ERR_FS_UNICODE
 TSK_ERR_FS_RECOVER
 TSK_ERR_FS_GENFS
 TSK_ERR_FS_CORRUPT
 TSK_ERR_FS_ATTR_NOTFOUND
 TSK_ERR_FS_MAX
 TSK_ERR_HDB_UNKTYPE
 TSK_ERR_HDB_UNSUPTYPE
 TSK_ERR_HDB_READDB
 TSK_ERR_HDB_READIDX
 TSK_ERR_HDB_ARG
 TSK_ERR_HDB_WRITE
 TSK_ERR_HDB_CREATE
 TSK_ERR_HDB_DELETE
 TSK_ERR_HDB_MISSING
 TSK_ERR_HDB_PROC
 TSK_ERR_HDB_OPEN
 TSK_ERR_HDB_CORRUPT
 TSK_ERR_HDB_MAX
 FALSE
 TRUE
 TSK_FS_BLOCK_TAG
 TSK_FS_ATTR_ID_DEFAULT
 TSK_FS_META_NAME_LIST_NSIZE
 TSK_FS_META_TYPE_STR_MAX
 TSK_FS_META_TAG
 TSK_FS_ORPHAN_STR
 TSK_FS_NAME_TYPE_STR_MAX
 TSK_FS_NAME_TAG
 TSK_FS_DIR_TAG
 TSK_FS_FILE_TAG
 TSK_FS_INFO_TAG
 TSK_FS_INFO_FS_ID_LEN
 TSK_VERSION_NUM
 TSK_VERSION_STR
 PRIX64
 PRIX32
 PRIX16
 TSK_ERR_AUX
 TSK_ERR_IMG
 TSK_ERR_VS
 TSK_ERR_FS
 TSK_ERR_HDB
 TSK_ERR_MASK
 TSK_ERR_AUX_MALLOC
 TSK_ERR_AUX_MAX
 TSK_ERR_IMG_NOFILE
 TSK_ERR_IMG_OFFSET
 TSK_ERR_IMG_UNKTYPE
 TSK_ERR_IMG_UNSUPTYPE
 TSK_ERR_IMG_OPEN
 TSK_ERR_IMG_STAT
 TSK_ERR_IMG_SEEK
 TSK_ERR_IMG_READ
 TSK_ERR_IMG_READ_OFF
 TSK_ERR_IMG_ARG
 TSK_ERR_IMG_MAGIC
 TSK_ERR_IMG_WRITE
 TSK_ERR_IMG_CONVERT
 TSK_ERR_IMG_PASSWD
 TSK_ERR_IMG_MAX
 TSK_ERR_VS_UNKTYPE
 TSK_ERR_VS_UNSUPTYPE
 TSK_ERR_VS_READ
 TSK_ERR_VS_MAGIC
 TSK_ERR_VS_WALK_RNG
 TSK_ERR_VS_BUF
 TSK_ERR_VS_BLK_NUM
 TSK_ERR_VS_ARG
 TSK_ERR_VS_MAX
 TSK_ERR_FS_UNKTYPE
 TSK_ERR_FS_UNSUPTYPE
 TSK_ERR_FS_UNSUPFUNC
 TSK_ERR_FS_WALK_RNG
 TSK_ERR_FS_READ
 TSK_ERR_FS_READ_OFF
 TSK_ERR_FS_ARG
 TSK_ERR_FS_BLK_NUM
 TSK_ERR_FS_INODE_NUM
 TSK_ERR_FS_INODE_COR
 TSK_ERR_FS_MAGIC
 TSK_ERR_FS_FWALK
 TSK_ERR_FS_WRITE
 TSK_ERR_FS_UNICODE
 TSK_ERR_FS_RECOVER
 TSK_ERR_FS_GENFS
 TSK_ERR_FS_CORRUPT
 TSK_ERR_FS_ATTR_NOTFOUND
 TSK_ERR_FS_MAX
 TSK_ERR_HDB_UNKTYPE
 TSK_ERR_HDB_UNSUPTYPE
 TSK_ERR_HDB_READDB
 TSK_ERR_HDB_READIDX
 TSK_ERR_HDB_ARG
 TSK_ERR_HDB_WRITE
 TSK_ERR_HDB_CREATE
 TSK_ERR_HDB_DELETE
 TSK_ERR_HDB_MISSING
 TSK_ERR_HDB_PROC
 TSK_ERR_HDB_OPEN
 TSK_ERR_HDB_CORRUPT
 TSK_ERR_HDB_MAX
 FALSE
 TRUE
***********************************************************************/
#include <Python.h>
#include "/home/mic/projects/aff4/python2.6/tsk/pytsk3.h"
#include "/home/mic/projects/aff4/python2.6/tsk/tsk3.h"
#include "/usr/local/include/tsk3/fs/tsk_fs.h"
#include "/usr/local/include/tsk3/base/tsk_base.h"

/* The following is a static array mapping CLASS() pointers to their
python wrappers. This is used to allow the correct wrapper to be
chosen depending on the object type found - regardless of the
prototype.

This is basically a safer way for us to cast the correct python type
depending on context rather than assuming a type based on the .h
definition. For example consider the function

AFFObject Resolver.open(uri, mode)

The .h file implies that an AFFObject object is returned, but this is
not true as most of the time an object of a derived class will be
returned. In C we cast the returned value to the correct type. In the
python wrapper we just instantiate the correct python object wrapper
at runtime depending on the actual returned type. We use this lookup
table to do so.
*/
static int TOTAL_CLASSES=0;

static struct python_wrapper_map_t {
       Object class_ref;
       PyTypeObject *python_type;
} python_wrappers[18];

/** This is a generic wrapper type */
typedef struct {
  PyObject_HEAD
  void *base;
  void *ctx;
} Gen_wrapper;

/* Create the relevant wrapper from the item based on the lookup
table.
*/
Gen_wrapper *new_class_wrapper(Object item) {
   int i;
   Gen_wrapper *result;
   Object cls;

   // Return None for a NULL pointer
   if(!item) {
     Py_INCREF(Py_None);
     return (Gen_wrapper *)Py_None;
   };

   // Search for subclasses
   for(cls=(Object)item->__class__; cls != cls->__super__; cls=cls->__super__) {
     for(i=0; i<TOTAL_CLASSES; i++) {
       if(python_wrappers[i].class_ref == cls) {
         PyErr_Clear();

         result = (Gen_wrapper *)_PyObject_New(python_wrappers[i].python_type);
         result->ctx = talloc_asprintf(NULL, "new_class_wrapper %s@%p", NAMEOF(item), item);
         result->base = (void *)item;

         return result;
       };
     };
   };

  PyErr_Format(PyExc_RuntimeError, "Unable to find a wrapper for object %s", NAMEOF(item));
  return NULL;
};

static PyObject *resolve_exception(char **error_buff) {
  enum _error_type *type = aff4_get_current_error(error_buff);
  switch(*type) {
case EProgrammingError:
    return PyExc_SystemError;
case EKeyError:
    return PyExc_KeyError;
case ERuntimeError:
    return PyExc_RuntimeError;
case EWarning:
    return PyExc_AssertionError;
default:
    return PyExc_RuntimeError;
};
};

static int type_check(PyObject *obj, PyTypeObject *type) {
   PyTypeObject *tmp;

   // Recurse through the inheritance tree and check if the types are expected
   if(obj)
     for(tmp = obj->ob_type; tmp && tmp != &PyBaseObject_Type; tmp = tmp->tp_base) {
       if(tmp == type) return 1;
     };

  return 0;
};


typedef struct {
  PyObject_HEAD
  AFF4ImgInfo base;
  void *ctx;
} pyAFF4ImgInfo; 

staticforward PyTypeObject AFF4ImgInfo_Type;

static int pyAFF4ImgInfo_init(pyAFF4ImgInfo *self, PyObject *args, PyObject *kwds);

static PyObject *pyAFF4ImgInfo_getattr(pyAFF4ImgInfo *self, PyObject *name);
static PyObject *pyAFF4ImgInfo_read(pyAFF4ImgInfo *self, PyObject *args, PyObject *kwds);
static PyObject *pyAFF4ImgInfo_close(pyAFF4ImgInfo *self, PyObject *args, PyObject *kwds);

typedef struct {
  PyObject_HEAD
  Object base;
  void *ctx;
} pyObject; 

staticforward PyTypeObject Object_Type;

static int pyObject_init(pyObject *self, PyObject *args, PyObject *kwds);

static PyObject *pyObject_getattr(pyObject *self, PyObject *name);
/*****************************************************
             Implementation
******************************************************/

static PyMethodDef AFF4ImgInfo_methods[] = {
     {"read",(PyCFunction)pyAFF4ImgInfo_read, METH_VARARGS|METH_KEYWORDS, "ssize_t AFF4ImgInfo.read(TSK_OFF_T off ,OUT char * buf, int len);\n\n\n Read a random buffer from the image\n"},
     {"close",(PyCFunction)pyAFF4ImgInfo_close, METH_VARARGS|METH_KEYWORDS, "void AFF4ImgInfo.close();\n\n\n Closes the image\n"},
     {NULL}  /* Sentinel */
};
static void
AFF4ImgInfo_dealloc(pyAFF4ImgInfo *self) {

    if(self->base) {
        //printf("Unlinking %s@%p\n", NAMEOF(self->base), self->base);
        talloc_free(self->ctx);
        self->base=NULL;
    };

 PyObject_Del(self);
};

static int pyAFF4ImgInfo_init(pyAFF4ImgInfo *self, PyObject *args, PyObject *kwds) {
ZString __attribute__((unused)) urn;
uint64_t  offset= 0;;
uint64_t  type= 0;;
static char *kwlist[] = {"urn","offset","type", NULL};

if(!PyArg_ParseTupleAndKeywords(args, kwds, "s|KK", kwlist, &urn,&offset,&type))
 goto error;


self->ctx = talloc_strdup(NULL, "AFF4ImgInfo");
 Py_BEGIN_ALLOW_THREADS
self->base = CONSTRUCT(AFF4ImgInfo, AFF4ImgInfo, Con, self->ctx, urn, offset, type);
Py_END_ALLOW_THREADS

       if(!CheckError(EZero)) {
         char *buffer;
         PyObject *exception = resolve_exception(&buffer);

         PyErr_Format(exception,
                    "%s", buffer);
         ClearError();
         goto error;
  } else if(!self->base) {
    PyErr_Format(PyExc_IOError, "Unable to construct class AFF4ImgInfo");
    goto error;
  };
  return 0;
error:
    return -1;
};


static PyObject *pyAFF4ImgInfo_getattr(pyAFF4ImgInfo *self, PyObject *pyname) {
  char *name;
  // Try to hand it off to the python native handler first
  PyObject *result = PyObject_GenericGetAttr((PyObject*)self, pyname);

  if(result) return result;

  PyErr_Clear();
  // No - nothing interesting was found by python
  name = PyString_AsString(pyname);

  if(!self->base) return PyErr_Format(PyExc_RuntimeError, "Wrapped object no longer valid");
  if(!name) return NULL;
  if(!strcmp(name, "__members__")) {
     PyObject *result = PyList_New(0);
     PyObject *tmp;
     PyMethodDef *i;

     if(!result) goto error;
 tmp = PyString_FromString("urn");
    PyList_Append(result, tmp); Py_DECREF(tmp);


    for(i=AFF4ImgInfo_methods; i->ml_name; i++) {
     tmp = PyString_FromString(i->ml_name);
    PyList_Append(result, tmp); Py_DECREF(tmp);
    }; 
     return result; 
   }

if(!strcmp(name, "urn")) {
    PyObject *py_result;
    Gen_wrapper *urn __attribute__((unused)) = NULL;


    {
       Object returned_object;

       ClearError();

       Py_BEGIN_ALLOW_THREADS
       returned_object = (Object)(((AFF4ImgInfo)self->base)->urn);
       Py_END_ALLOW_THREADS

       if(!CheckError(EZero)) {
         char *buffer;
         PyObject *exception = resolve_exception(&buffer);

         PyErr_Format(exception,
                    "%s", buffer);
         ClearError();
         goto error;

       // A NULL return without errors means we return None
       } else if(!returned_object) {
         urn = (Gen_wrapper *)Py_None;
         Py_INCREF(Py_None);
       } else {
         //printf("%s: Wrapping %s@%p\n", __FUNCTION__, NAMEOF(returned_object), returned_object);
         urn = new_class_wrapper(returned_object);
         if(!urn) goto error;
           talloc_reference(urn->ctx, urn->base);
       };
    }

    py_result = (PyObject *)urn;

    return py_result;
};

  return PyObject_GenericGetAttr((PyObject *)self, pyname);
error:
return NULL;
}


/********************************************************
Autogenerated wrapper for function:
ssize_t AFF4ImgInfo.read(TSK_OFF_T off ,OUT char * buf, int len);
********************************************************/

static PyObject *pyAFF4ImgInfo_read(pyAFF4ImgInfo *self, PyObject *args, PyObject *kwds) {
       PyObject *returned_result, *py_result;
uint64_t  __attribute__((unused)) func_return;
uint64_t  __attribute__((unused)) off;
char *buf=NULL; Py_ssize_t len=0;
PyObject *tmp_buf;
static char *kwlist[] = {"off","len", NULL};

if(!PyArg_ParseTupleAndKeywords(args, kwds, "Kl|", kwlist, &off,&len))
 goto error;

// Make sure that we have something valid to wrap
if(!self->base) return PyErr_Format(PyExc_RuntimeError, "AFF4ImgInfo object no longer valid");
// Precall preparations
PyErr_Clear();
tmp_buf = PyString_FromStringAndSize(NULL, len);
if(!tmp_buf) goto error;
PyString_AsStringAndSize(tmp_buf, &buf, (Py_ssize_t *)&len);
// Check the function is implemented
  {  void *method = ((AFF4ImgInfo)self->base)->read;
     if(!method || (void *)unimplemented == (void *)method) {
         PyErr_Format(PyExc_RuntimeError, "AFF4ImgInfo.read is not implemented");
         goto error;
     };
  };

// Make the call
 ClearError();Py_BEGIN_ALLOW_THREADS
func_return = ((AFF4ImgInfo)self->base)->read(((AFF4ImgInfo)self->base), off, (OUT char *)buf, (int)len);
Py_END_ALLOW_THREADS
//Check for errors
         if(!CheckError(EZero)) {
                char *buffer;
                PyObject *exception = resolve_exception(&buffer);

                PyErr_Format(exception,
                            "%s", buffer);
                ClearError();
                goto error;
         }
// Postcall preparations

// prepare results
 _PyString_Resize(&tmp_buf, func_return); 
py_result = tmp_buf;
returned_result = py_result;
return returned_result;

// error conditions:
error:
    return NULL;

};


/********************************************************
Autogenerated wrapper for function:
void AFF4ImgInfo.close();
********************************************************/

static PyObject *pyAFF4ImgInfo_close(pyAFF4ImgInfo *self, PyObject *args, PyObject *kwds) {
       PyObject *returned_result, *py_result;
// Make sure that we have something valid to wrap
if(!self->base) return PyErr_Format(PyExc_RuntimeError, "AFF4ImgInfo object no longer valid");
// Precall preparations
// Check the function is implemented
  {  void *method = ((AFF4ImgInfo)self->base)->close;
     if(!method || (void *)unimplemented == (void *)method) {
         PyErr_Format(PyExc_RuntimeError, "AFF4ImgInfo.close is not implemented");
         goto error;
     };
  };

// Make the call
 ClearError();Py_BEGIN_ALLOW_THREADS
((AFF4ImgInfo)self->base)->close(((AFF4ImgInfo)self->base));
Py_END_ALLOW_THREADS
//Check for errors
         if(!CheckError(EZero)) {
                char *buffer;
                PyObject *exception = resolve_exception(&buffer);

                PyErr_Format(exception,
                            "%s", buffer);
                ClearError();
                goto error;
         }
// Postcall preparations

// prepare results
Py_INCREF(Py_None); py_result = Py_None;
returned_result = py_result;
return returned_result;

// error conditions:
error:
    return NULL;

};



static int
AFF4ImgInfo_nonzero(pyAFF4ImgInfo *v)
{
        return v->base != 0;
};


static PyNumberMethods AFF4ImgInfo_as_number = {
        (binaryfunc)    0,       /*nb_add*/
        (binaryfunc)    0,       /*nb_subtract*/
        (binaryfunc)    0,       /*nb_multiply*/
                        0,       /*nb_divide*/
                        0,       /*nb_remainder*/
                        0,       /*nb_divmod*/
                        0,       /*nb_power*/
        (unaryfunc)     0,       /*nb_negative*/
        (unaryfunc)     0,       /*tp_positive*/
        (unaryfunc)     0,       /*tp_absolute*/
        (inquiry)       AFF4ImgInfo_nonzero,   /*tp_nonzero*/
        (unaryfunc)     0,       /*nb_invert*/
                        0,       /*nb_lshift*/
        (binaryfunc)    0,       /*nb_rshift*/
                        0,       /*nb_and*/
                        0,       /*nb_xor*/
                        0,       /*nb_or*/
                        0,       /*nb_coerce*/
                        0,       /*nb_int*/
                        0,       /*nb_long*/
                        0,       /*nb_float*/
                        0,       /*nb_oct*/
                        0,       /*nb_hex*/
        0,                              /* nb_inplace_add */
        0,                              /* nb_inplace_subtract */
        0,                              /* nb_inplace_multiply */
        0,                              /* nb_inplace_divide */
        0,                              /* nb_inplace_remainder */
        0,                              /* nb_inplace_power */
        0,                              /* nb_inplace_lshift */
        0,                              /* nb_inplace_rshift */
        0,                              /* nb_inplace_and */
        0,                              /* nb_inplace_xor */
        0,                              /* nb_inplace_or */
        0,                              /* nb_floor_divide */
        0,                              /* nb_true_divide */
        0,                              /* nb_inplace_floor_divide */
        0,                              /* nb_inplace_true_divide */
        0,                              /* nb_index */
};

static PyTypeObject AFF4ImgInfo_Type = {
    PyObject_HEAD_INIT(NULL)
    0,                         /* ob_size */
    "pytsk3.AFF4ImgInfo",               /* tp_name */
    sizeof(pyAFF4ImgInfo),            /* tp_basicsize */
    0,                         /* tp_itemsize */
    (destructor)AFF4ImgInfo_dealloc,/* tp_dealloc */
    0,                         /* tp_print */
    0,                         /* tp_getattr */
    0,                         /* tp_setattr */
    0,                         /* tp_compare */
    0,                         /* tp_repr */
    &AFF4ImgInfo_as_number,      /* tp_as_number */
    0,                         /* tp_as_sequence */
    0,                         /* tp_as_mapping */
    0,                         /* tp_hash */
    0,                         /* tp_call */
    0,                         /* tp_str */
    (getattrofunc)pyAFF4ImgInfo_getattr,                         /* tp_getattro */
    0,                         /* tp_setattro */
    0,                         /* tp_as_buffer */
    Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,        /* tp_flags */
    "AFF4ImgInfo:  This is an image info object based on an AFF4 object.\n\n    Before we can use libtsk we need to instantiate one of these from\n    a base URN.\n ",     /* tp_doc */
    0,	                       /* tp_traverse */
    0,                         /* tp_clear */
    0,                         /* tp_richcompare */
    0,                         /* tp_weaklistoffset */
    0,                         /* tp_iter */
    0,                         /* tp_iternext */
    AFF4ImgInfo_methods,            /* tp_methods */
    0,                         /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)pyAFF4ImgInfo_init,      /* tp_init */
    0,                         /* tp_alloc */
    0,                         /* tp_new */
};
static PyMethodDef Object_methods[] = {
     {NULL}  /* Sentinel */
};
static void
Object_dealloc(pyObject *self) {

    if(self->base) {
        //printf("Unlinking %s@%p\n", NAMEOF(self->base), self->base);
        talloc_free(self->ctx);
        self->base=NULL;
    };

 PyObject_Del(self);
};

static int pyObject_init(pyObject *self, PyObject *args, PyObject *kwds) {
return 0;};


static PyObject *pyObject_getattr(pyObject *self, PyObject *pyname) {
  char *name;
  // Try to hand it off to the python native handler first
  PyObject *result = PyObject_GenericGetAttr((PyObject*)self, pyname);

  if(result) return result;

  PyErr_Clear();
  // No - nothing interesting was found by python
  name = PyString_AsString(pyname);

  if(!self->base) return PyErr_Format(PyExc_RuntimeError, "Wrapped object no longer valid");
  if(!name) return NULL;
  if(!strcmp(name, "__members__")) {
     PyObject *result = PyList_New(0);
     PyObject *tmp;
     PyMethodDef *i;

     if(!result) goto error;


    for(i=Object_methods; i->ml_name; i++) {
     tmp = PyString_FromString(i->ml_name);
    PyList_Append(result, tmp); Py_DECREF(tmp);
    }; 
     return result; 
   }


  return PyObject_GenericGetAttr((PyObject *)self, pyname);
error:
return NULL;
}



static int
Object_nonzero(pyObject *v)
{
        return v->base != 0;
};


static PyNumberMethods Object_as_number = {
        (binaryfunc)    0,       /*nb_add*/
        (binaryfunc)    0,       /*nb_subtract*/
        (binaryfunc)    0,       /*nb_multiply*/
                        0,       /*nb_divide*/
                        0,       /*nb_remainder*/
                        0,       /*nb_divmod*/
                        0,       /*nb_power*/
        (unaryfunc)     0,       /*nb_negative*/
        (unaryfunc)     0,       /*tp_positive*/
        (unaryfunc)     0,       /*tp_absolute*/
        (inquiry)       Object_nonzero,   /*tp_nonzero*/
        (unaryfunc)     0,       /*nb_invert*/
                        0,       /*nb_lshift*/
        (binaryfunc)    0,       /*nb_rshift*/
                        0,       /*nb_and*/
                        0,       /*nb_xor*/
                        0,       /*nb_or*/
                        0,       /*nb_coerce*/
                        0,       /*nb_int*/
                        0,       /*nb_long*/
                        0,       /*nb_float*/
                        0,       /*nb_oct*/
                        0,       /*nb_hex*/
        0,                              /* nb_inplace_add */
        0,                              /* nb_inplace_subtract */
        0,                              /* nb_inplace_multiply */
        0,                              /* nb_inplace_divide */
        0,                              /* nb_inplace_remainder */
        0,                              /* nb_inplace_power */
        0,                              /* nb_inplace_lshift */
        0,                              /* nb_inplace_rshift */
        0,                              /* nb_inplace_and */
        0,                              /* nb_inplace_xor */
        0,                              /* nb_inplace_or */
        0,                              /* nb_floor_divide */
        0,                              /* nb_true_divide */
        0,                              /* nb_inplace_floor_divide */
        0,                              /* nb_inplace_true_divide */
        0,                              /* nb_index */
};

static PyTypeObject Object_Type = {
    PyObject_HEAD_INIT(NULL)
    0,                         /* ob_size */
    "pytsk3.Object",               /* tp_name */
    sizeof(pyObject),            /* tp_basicsize */
    0,                         /* tp_itemsize */
    (destructor)Object_dealloc,/* tp_dealloc */
    0,                         /* tp_print */
    0,                         /* tp_getattr */
    0,                         /* tp_setattr */
    0,                         /* tp_compare */
    0,                         /* tp_repr */
    &Object_as_number,      /* tp_as_number */
    0,                         /* tp_as_sequence */
    0,                         /* tp_as_mapping */
    0,                         /* tp_hash */
    0,                         /* tp_call */
    0,                         /* tp_str */
    (getattrofunc)pyObject_getattr,                         /* tp_getattro */
    0,                         /* tp_setattro */
    0,                         /* tp_as_buffer */
    Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,        /* tp_flags */
    "Object:  Base object\n",     /* tp_doc */
    0,	                       /* tp_traverse */
    0,                         /* tp_clear */
    0,                         /* tp_richcompare */
    0,                         /* tp_weaklistoffset */
    0,                         /* tp_iter */
    0,                         /* tp_iternext */
    Object_methods,            /* tp_methods */
    0,                         /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)pyObject_init,      /* tp_init */
    0,                         /* tp_alloc */
    0,                         /* tp_new */
};

static PyMethodDef pytsk3_methods[] = {
     {NULL}  /* Sentinel */
};

PyMODINIT_FUNC initpytsk3(void) {
   /* Make sure threads are enabled */
   PyEval_InitThreads();

   /* create module */
   PyObject *m = Py_InitModule3("pytsk3", pytsk3_methods,
                                   "pytsk3 module.");
   PyObject *d = PyModule_GetDict(m);
   PyObject *tmp;

 Object_Type.tp_new = PyType_GenericNew;
 if (PyType_Ready(&Object_Type) < 0)
     return;

 Py_INCREF((PyObject *)&Object_Type);
 PyModule_AddObject(m, "Object", (PyObject *)&Object_Type);
 AFF4ImgInfo_Type.tp_base = &Object_Type;
 AFF4ImgInfo_Type.tp_new = PyType_GenericNew;
 if (PyType_Ready(&AFF4ImgInfo_Type) < 0)
     return;

 Py_INCREF((PyObject *)&AFF4ImgInfo_Type);
 PyModule_AddObject(m, "AFF4ImgInfo", (PyObject *)&AFF4ImgInfo_Type);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_BLOCK_TAG); 

 PyDict_SetItemString(d, "TSK_FS_BLOCK_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_ATTR_ID_DEFAULT); 

 PyDict_SetItemString(d, "TSK_FS_ATTR_ID_DEFAULT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_META_NAME_LIST_NSIZE); 

 PyDict_SetItemString(d, "TSK_FS_META_NAME_LIST_NSIZE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_META_TYPE_STR_MAX); 

 PyDict_SetItemString(d, "TSK_FS_META_TYPE_STR_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_META_TAG); 

 PyDict_SetItemString(d, "TSK_FS_META_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)TSK_FS_ORPHAN_STR); 

 PyDict_SetItemString(d, "TSK_FS_ORPHAN_STR", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_NAME_TYPE_STR_MAX); 

 PyDict_SetItemString(d, "TSK_FS_NAME_TYPE_STR_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_NAME_TAG); 

 PyDict_SetItemString(d, "TSK_FS_NAME_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_DIR_TAG); 

 PyDict_SetItemString(d, "TSK_FS_DIR_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_FILE_TAG); 

 PyDict_SetItemString(d, "TSK_FS_FILE_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_INFO_TAG); 

 PyDict_SetItemString(d, "TSK_FS_INFO_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_INFO_FS_ID_LEN); 

 PyDict_SetItemString(d, "TSK_FS_INFO_FS_ID_LEN", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_VERSION_NUM); 

 PyDict_SetItemString(d, "TSK_VERSION_NUM", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)TSK_VERSION_STR); 

 PyDict_SetItemString(d, "TSK_VERSION_STR", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)PRIX64); 

 PyDict_SetItemString(d, "PRIX64", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)PRIX32); 

 PyDict_SetItemString(d, "PRIX32", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)PRIX16); 

 PyDict_SetItemString(d, "PRIX16", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_AUX); 

 PyDict_SetItemString(d, "TSK_ERR_AUX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG); 

 PyDict_SetItemString(d, "TSK_ERR_IMG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS); 

 PyDict_SetItemString(d, "TSK_ERR_VS", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS); 

 PyDict_SetItemString(d, "TSK_ERR_FS", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB); 

 PyDict_SetItemString(d, "TSK_ERR_HDB", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_MASK); 

 PyDict_SetItemString(d, "TSK_ERR_MASK", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_AUX_MALLOC); 

 PyDict_SetItemString(d, "TSK_ERR_AUX_MALLOC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_AUX_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_AUX_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_NOFILE); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_NOFILE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_OFFSET); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_OFFSET", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_UNKTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_UNKTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_UNSUPTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_UNSUPTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_OPEN); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_OPEN", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_STAT); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_STAT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_SEEK); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_SEEK", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_READ); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_READ", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_READ_OFF); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_READ_OFF", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_ARG); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_ARG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_MAGIC); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_MAGIC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_WRITE); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_WRITE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_CONVERT); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_CONVERT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_PASSWD); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_PASSWD", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_UNKTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_VS_UNKTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_UNSUPTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_VS_UNSUPTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_READ); 

 PyDict_SetItemString(d, "TSK_ERR_VS_READ", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_MAGIC); 

 PyDict_SetItemString(d, "TSK_ERR_VS_MAGIC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_WALK_RNG); 

 PyDict_SetItemString(d, "TSK_ERR_VS_WALK_RNG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_BUF); 

 PyDict_SetItemString(d, "TSK_ERR_VS_BUF", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_BLK_NUM); 

 PyDict_SetItemString(d, "TSK_ERR_VS_BLK_NUM", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_ARG); 

 PyDict_SetItemString(d, "TSK_ERR_VS_ARG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_VS_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_UNKTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_FS_UNKTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_UNSUPTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_FS_UNSUPTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_UNSUPFUNC); 

 PyDict_SetItemString(d, "TSK_ERR_FS_UNSUPFUNC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_WALK_RNG); 

 PyDict_SetItemString(d, "TSK_ERR_FS_WALK_RNG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_READ); 

 PyDict_SetItemString(d, "TSK_ERR_FS_READ", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_READ_OFF); 

 PyDict_SetItemString(d, "TSK_ERR_FS_READ_OFF", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_ARG); 

 PyDict_SetItemString(d, "TSK_ERR_FS_ARG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_BLK_NUM); 

 PyDict_SetItemString(d, "TSK_ERR_FS_BLK_NUM", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_INODE_NUM); 

 PyDict_SetItemString(d, "TSK_ERR_FS_INODE_NUM", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_INODE_COR); 

 PyDict_SetItemString(d, "TSK_ERR_FS_INODE_COR", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_MAGIC); 

 PyDict_SetItemString(d, "TSK_ERR_FS_MAGIC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_FWALK); 

 PyDict_SetItemString(d, "TSK_ERR_FS_FWALK", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_WRITE); 

 PyDict_SetItemString(d, "TSK_ERR_FS_WRITE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_UNICODE); 

 PyDict_SetItemString(d, "TSK_ERR_FS_UNICODE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_RECOVER); 

 PyDict_SetItemString(d, "TSK_ERR_FS_RECOVER", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_GENFS); 

 PyDict_SetItemString(d, "TSK_ERR_FS_GENFS", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_CORRUPT); 

 PyDict_SetItemString(d, "TSK_ERR_FS_CORRUPT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_ATTR_NOTFOUND); 

 PyDict_SetItemString(d, "TSK_ERR_FS_ATTR_NOTFOUND", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_FS_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_UNKTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_UNKTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_UNSUPTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_UNSUPTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_READDB); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_READDB", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_READIDX); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_READIDX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_ARG); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_ARG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_WRITE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_WRITE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_CREATE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_CREATE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_DELETE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_DELETE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_MISSING); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_MISSING", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_PROC); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_PROC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_OPEN); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_OPEN", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_CORRUPT); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_CORRUPT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)FALSE); 

 PyDict_SetItemString(d, "FALSE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TRUE); 

 PyDict_SetItemString(d, "TRUE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_BLOCK_TAG); 

 PyDict_SetItemString(d, "TSK_FS_BLOCK_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_ATTR_ID_DEFAULT); 

 PyDict_SetItemString(d, "TSK_FS_ATTR_ID_DEFAULT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_META_NAME_LIST_NSIZE); 

 PyDict_SetItemString(d, "TSK_FS_META_NAME_LIST_NSIZE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_META_TYPE_STR_MAX); 

 PyDict_SetItemString(d, "TSK_FS_META_TYPE_STR_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_META_TAG); 

 PyDict_SetItemString(d, "TSK_FS_META_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)TSK_FS_ORPHAN_STR); 

 PyDict_SetItemString(d, "TSK_FS_ORPHAN_STR", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_NAME_TYPE_STR_MAX); 

 PyDict_SetItemString(d, "TSK_FS_NAME_TYPE_STR_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_NAME_TAG); 

 PyDict_SetItemString(d, "TSK_FS_NAME_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_DIR_TAG); 

 PyDict_SetItemString(d, "TSK_FS_DIR_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_FILE_TAG); 

 PyDict_SetItemString(d, "TSK_FS_FILE_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_INFO_TAG); 

 PyDict_SetItemString(d, "TSK_FS_INFO_TAG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_FS_INFO_FS_ID_LEN); 

 PyDict_SetItemString(d, "TSK_FS_INFO_FS_ID_LEN", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_VERSION_NUM); 

 PyDict_SetItemString(d, "TSK_VERSION_NUM", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)TSK_VERSION_STR); 

 PyDict_SetItemString(d, "TSK_VERSION_STR", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)PRIX64); 

 PyDict_SetItemString(d, "PRIX64", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)PRIX32); 

 PyDict_SetItemString(d, "PRIX32", tmp);
 Py_DECREF(tmp);
 tmp = PyString_FromString((char *)PRIX16); 

 PyDict_SetItemString(d, "PRIX16", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_AUX); 

 PyDict_SetItemString(d, "TSK_ERR_AUX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG); 

 PyDict_SetItemString(d, "TSK_ERR_IMG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS); 

 PyDict_SetItemString(d, "TSK_ERR_VS", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS); 

 PyDict_SetItemString(d, "TSK_ERR_FS", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB); 

 PyDict_SetItemString(d, "TSK_ERR_HDB", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_MASK); 

 PyDict_SetItemString(d, "TSK_ERR_MASK", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_AUX_MALLOC); 

 PyDict_SetItemString(d, "TSK_ERR_AUX_MALLOC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_AUX_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_AUX_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_NOFILE); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_NOFILE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_OFFSET); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_OFFSET", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_UNKTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_UNKTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_UNSUPTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_UNSUPTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_OPEN); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_OPEN", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_STAT); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_STAT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_SEEK); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_SEEK", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_READ); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_READ", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_READ_OFF); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_READ_OFF", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_ARG); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_ARG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_MAGIC); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_MAGIC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_WRITE); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_WRITE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_CONVERT); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_CONVERT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_PASSWD); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_PASSWD", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_IMG_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_IMG_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_UNKTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_VS_UNKTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_UNSUPTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_VS_UNSUPTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_READ); 

 PyDict_SetItemString(d, "TSK_ERR_VS_READ", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_MAGIC); 

 PyDict_SetItemString(d, "TSK_ERR_VS_MAGIC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_WALK_RNG); 

 PyDict_SetItemString(d, "TSK_ERR_VS_WALK_RNG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_BUF); 

 PyDict_SetItemString(d, "TSK_ERR_VS_BUF", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_BLK_NUM); 

 PyDict_SetItemString(d, "TSK_ERR_VS_BLK_NUM", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_ARG); 

 PyDict_SetItemString(d, "TSK_ERR_VS_ARG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_VS_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_VS_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_UNKTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_FS_UNKTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_UNSUPTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_FS_UNSUPTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_UNSUPFUNC); 

 PyDict_SetItemString(d, "TSK_ERR_FS_UNSUPFUNC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_WALK_RNG); 

 PyDict_SetItemString(d, "TSK_ERR_FS_WALK_RNG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_READ); 

 PyDict_SetItemString(d, "TSK_ERR_FS_READ", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_READ_OFF); 

 PyDict_SetItemString(d, "TSK_ERR_FS_READ_OFF", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_ARG); 

 PyDict_SetItemString(d, "TSK_ERR_FS_ARG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_BLK_NUM); 

 PyDict_SetItemString(d, "TSK_ERR_FS_BLK_NUM", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_INODE_NUM); 

 PyDict_SetItemString(d, "TSK_ERR_FS_INODE_NUM", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_INODE_COR); 

 PyDict_SetItemString(d, "TSK_ERR_FS_INODE_COR", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_MAGIC); 

 PyDict_SetItemString(d, "TSK_ERR_FS_MAGIC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_FWALK); 

 PyDict_SetItemString(d, "TSK_ERR_FS_FWALK", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_WRITE); 

 PyDict_SetItemString(d, "TSK_ERR_FS_WRITE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_UNICODE); 

 PyDict_SetItemString(d, "TSK_ERR_FS_UNICODE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_RECOVER); 

 PyDict_SetItemString(d, "TSK_ERR_FS_RECOVER", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_GENFS); 

 PyDict_SetItemString(d, "TSK_ERR_FS_GENFS", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_CORRUPT); 

 PyDict_SetItemString(d, "TSK_ERR_FS_CORRUPT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_ATTR_NOTFOUND); 

 PyDict_SetItemString(d, "TSK_ERR_FS_ATTR_NOTFOUND", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_FS_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_FS_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_UNKTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_UNKTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_UNSUPTYPE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_UNSUPTYPE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_READDB); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_READDB", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_READIDX); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_READIDX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_ARG); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_ARG", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_WRITE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_WRITE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_CREATE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_CREATE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_DELETE); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_DELETE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_MISSING); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_MISSING", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_PROC); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_PROC", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_OPEN); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_OPEN", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_CORRUPT); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_CORRUPT", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TSK_ERR_HDB_MAX); 

 PyDict_SetItemString(d, "TSK_ERR_HDB_MAX", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)FALSE); 

 PyDict_SetItemString(d, "FALSE", tmp);
 Py_DECREF(tmp);
 tmp = PyLong_FromUnsignedLongLong((int)TRUE); 

 PyDict_SetItemString(d, "TRUE", tmp);
 Py_DECREF(tmp);

talloc_set_log_fn((void *)printf);
AFF4_Init();

python_wrappers[TOTAL_CLASSES].class_ref = (Object)&__AFF4ImgInfo;
python_wrappers[TOTAL_CLASSES++].python_type = &AFF4ImgInfo_Type;
python_wrappers[TOTAL_CLASSES].class_ref = (Object)&__Object;
python_wrappers[TOTAL_CLASSES++].python_type = &Object_Type;
}

