Import("env")
import pdb
import SCons.Util, SCons.Subst

env = env.Clone()

source_files = """
class.c talloc.c
misc.c zip.c stringio.c resolver.c rdf.c  libaff4.c image.c map.c  encode.c queue.c
"""
env.Append(CPPFLAGS = ['-DHAVE_VA_COPY'])

library = env.VersionedSharedLibrary("libaff4", '0', Split(source_files))
env.InstallVersionedSharedLibrary("${prefix}/lib/", library)
env.Alias('install', '${prefix}')

