import SconsUtils.utils as utils
import pdb

Import("env")

common_files = """
common.o
"""

programs = """aff4imager.c raid_reconstructor.c"""

for prog in Split(programs):
    prog = env.Program([prog] + Split(common_files),
                       LIBS='aff4', LIBPATH="#lib/")

env.Program("aff4fuse", ['affuse.c'] + Split(common_files), LIBS=['aff4', 'fuse'])
env.Install("$prefix/bin/", Split("aff4fuse aff4imager raid_reconstructor"))
