Import("env")

common_files = """
common.o
"""

programs = """aff4imager.c raid_reconstructor.c"""

for prog in Split(programs):
    env.Program([prog] + Split(common_files), LIBS='aff4', LIBPATH="#libs/")

env.Program(['affuse.c'] + Split(common_files), LIBS=['aff4', 'fuse'], LIBPATH="#libs/")
