import pyaff4

PYFLAG_NAMESPACE = "pyflag://"
PYFLAG_COLUMN = PYFLAG_NAMESPACE + "column"
PYFLAG_TABLE = PYFLAG_NAMESPACE + "table"

SOURCE_IP = PYFLAG_NAMESPACE + "ip/source"
DESTINATION_IP = PYFLAG_NAMESPACE + "ip/dest"
HTTP_URL = PYFLAG_NAMESPACE + "http/url"
HTTP_METHOD = PYFLAG_NAMESPACE + "http/method"
HTTP_CODE = PYFLAG_NAMESPACE + "http/code"
HOST_TLD  = PYFLAG_NAMESPACE + "host/tld"
TIMESTAMP_CREATED = PYFLAG_NAMESPACE + "timestamp/created"

RDF_DATATYPE = pyaff4.RDF_NAMESPACE + "dataType"
RDF_TYPE = pyaff4.RDF_NAMESPACE + "type"
