PYFLAG_NAMESPACE = "pyflag://"

SOURCE_IP = PYFLAG_NAMESPACE + "ip/source"
DESTINATION_IP = PYFLAG_NAMESPACE + "ip/dest"
HTTP_URL = PYFLAG_NAMESPACE + "http/url"
HTTP_METHOD = PYFLAG_NAMESPACE + "http/method"
HTTP_CODE = PYFLAG_NAMESPACE + "http/code"
HOST_TLD  = PYFLAG_NAMESPACE + "host/tld"
